[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Required to prevent physical reset loops on some generic ESP32-CAM boards
monitor_rts = 0
monitor_dtr = 0
